services:
  cadvisor:
    image: gcr.io/cadvisor/cadvisor:v0.52.0
    ports:
      - "8080:8080"
    volumes:
      - /:/rootfs:ro
      - /var/run:/var/run:ro
      - /sys:/sys:ro
      - /var/lib/docker/:/var/lib/docker:ro
    networks:
      - observability

  prometheus:
    image: prom/prometheus:latest
    ports:
      - "9090:9090"
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml:ro

  grafana:
    image: grafana/grafana:latest
    ports:
      - "9100:3000"
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=${GF_SECURITY_ADMIN_PASSWORD}
      - GF_PROVISIONING_DATASOURCES_PROMETHEUS_NAME=${GF_PROVISIONING_DATASOURCES_PROMETHEUS_NAME}
      - GF_PROVISIONING_DATASOURCES_PROMETHEUS_TYPE=${GF_PROVISIONING_DATASOURCES_PROMETHEUS_TYPE}
      - GF_PROVISIONING_DATASOURCES_PROMETHEUS_URL=${GF_PROVISIONING_DATASOURCES_PROMETHEUS_URL}
    volumes:
      - ./dashboards/:/var/lib/grafana/dashboards/:ro
      - ./provisioning/:/etc/grafana/provisioning/:ro

networks:
  observability:
    external: true
